name: helloworld
description: ProcessaiProject

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.5.0
  http: ^1.2.2
  js: ^0.6.3
  mime_type: ^1.0.0
  intl: ^0.19.0
  provider: ^6.0.3  # O la versión más reciente
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.4
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  loading_btn: ^1.0.3
  auto_size_widget: ^0.0.4
  web_socket_channel: ^3.0.1
  socket_io_client: ^2.0.3+1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/pailogo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
